{% set name = "grabseqs" %}
{% set version = "0.5.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  entry_points:
    - grabseqs = grabseqslib:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pandas
    - python {{ python }}
    - requests
    - requests_html
  run:
    - pandas
    - python
    - requests
    - requests_html
    - sra-tools
    - pigz
    - wget

test:
  imports:
    - grabseqslib
  commands:
    - grabseqs --help

about:
  home: "https://github.com/louiejtaylor/grabseqs"
  license: MIT
  license_family: MIT
  summary: "Easily download reads from next-gen sequencing repositories like NCBI SRA"

extra:
  recipe-maintainers:
    - louiejtaylor
