{% set version = "0.2.9" %}

package:
  name: grabseqs
  version: '{{ version }}'

source:
  url: https://github.com/louiejtaylor/grabseqs/archive/{{ version }}.tar.gz

requirements:
  run:
    - sra-tools>2.9
    - python>3
    - requests
    - argparse
    - pigz
    - wget 

test:
  commands:
    - grabseqs -v

about:
  home: https://github.com/louiejtaylor/grabseqs
  license: MIT
  license_family: MIT
  summary: grabseqs simplifies downloading reads in bulk from SRA projects
  dev_url: https://github.com/louiejtaylor/grabseqs

